// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package s3

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
)

const opListBucketInventoryConfigurations = "ListBucketInventoryConfigurations"

// ListBucketInventoryConfigurationsRequest returns a request value for making API operation for
// Amazon Simple Storage Service.
//
// Returns a list of inventory configurations for the bucket.
//
//    // Example sending a request using ListBucketInventoryConfigurationsRequest.
//    req := client.ListBucketInventoryConfigurationsRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/s3-2006-03-01/ListBucketInventoryConfigurations
func (c *Client) ListBucketInventoryConfigurationsRequest(input *types.ListBucketInventoryConfigurationsInput) ListBucketInventoryConfigurationsRequest {
	op := &aws.Operation{
		Name:       opListBucketInventoryConfigurations,
		HTTPMethod: "GET",
		HTTPPath:   "/{Bucket}?inventory",
	}

	if input == nil {
		input = &types.ListBucketInventoryConfigurationsInput{}
	}

	req := c.newRequest(op, input, &types.ListBucketInventoryConfigurationsOutput{})
	return ListBucketInventoryConfigurationsRequest{Request: req, Input: input, Copy: c.ListBucketInventoryConfigurationsRequest}
}

// ListBucketInventoryConfigurationsRequest is the request type for the
// ListBucketInventoryConfigurations API operation.
type ListBucketInventoryConfigurationsRequest struct {
	*aws.Request
	Input *types.ListBucketInventoryConfigurationsInput
	Copy  func(*types.ListBucketInventoryConfigurationsInput) ListBucketInventoryConfigurationsRequest
}

// Send marshals and sends the ListBucketInventoryConfigurations API request.
func (r ListBucketInventoryConfigurationsRequest) Send(ctx context.Context) (*ListBucketInventoryConfigurationsResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &ListBucketInventoryConfigurationsResponse{
		ListBucketInventoryConfigurationsOutput: r.Request.Data.(*types.ListBucketInventoryConfigurationsOutput),
		response:                                &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// ListBucketInventoryConfigurationsResponse is the response type for the
// ListBucketInventoryConfigurations API operation.
type ListBucketInventoryConfigurationsResponse struct {
	*types.ListBucketInventoryConfigurationsOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// ListBucketInventoryConfigurations request.
func (r *ListBucketInventoryConfigurationsResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
