// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package s3

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/private/protocol"
	"github.com/aws/aws-sdk-go-v2/private/protocol/restxml"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
)

const opPutBucketAccelerateConfiguration = "PutBucketAccelerateConfiguration"

// PutBucketAccelerateConfigurationRequest returns a request value for making API operation for
// Amazon Simple Storage Service.
//
// Sets the accelerate configuration of an existing bucket.
//
//    // Example sending a request using PutBucketAccelerateConfigurationRequest.
//    req := client.PutBucketAccelerateConfigurationRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/s3-2006-03-01/PutBucketAccelerateConfiguration
func (c *Client) PutBucketAccelerateConfigurationRequest(input *types.PutBucketAccelerateConfigurationInput) PutBucketAccelerateConfigurationRequest {
	op := &aws.Operation{
		Name:       opPutBucketAccelerateConfiguration,
		HTTPMethod: "PUT",
		HTTPPath:   "/{Bucket}?accelerate",
	}

	if input == nil {
		input = &types.PutBucketAccelerateConfigurationInput{}
	}

	req := c.newRequest(op, input, &types.PutBucketAccelerateConfigurationOutput{})
	req.Handlers.Unmarshal.Remove(restxml.UnmarshalHandler)
	req.Handlers.Unmarshal.PushBackNamed(protocol.UnmarshalDiscardBodyHandler)
	return PutBucketAccelerateConfigurationRequest{Request: req, Input: input, Copy: c.PutBucketAccelerateConfigurationRequest}
}

// PutBucketAccelerateConfigurationRequest is the request type for the
// PutBucketAccelerateConfiguration API operation.
type PutBucketAccelerateConfigurationRequest struct {
	*aws.Request
	Input *types.PutBucketAccelerateConfigurationInput
	Copy  func(*types.PutBucketAccelerateConfigurationInput) PutBucketAccelerateConfigurationRequest
}

// Send marshals and sends the PutBucketAccelerateConfiguration API request.
func (r PutBucketAccelerateConfigurationRequest) Send(ctx context.Context) (*PutBucketAccelerateConfigurationResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &PutBucketAccelerateConfigurationResponse{
		PutBucketAccelerateConfigurationOutput: r.Request.Data.(*types.PutBucketAccelerateConfigurationOutput),
		response:                               &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// PutBucketAccelerateConfigurationResponse is the response type for the
// PutBucketAccelerateConfiguration API operation.
type PutBucketAccelerateConfigurationResponse struct {
	*types.PutBucketAccelerateConfigurationOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// PutBucketAccelerateConfiguration request.
func (r *PutBucketAccelerateConfigurationResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
