// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package aws_jsonrpc service, marshal.go contains the generated operation marshalers and methods on it.

package aws_jsonrpc

import (
	"bytes"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/awserr"
	"github.com/aws/aws-sdk-go-v2/private/protocol/jsonrpc"
	"github.com/aws/aws-sdk-go-v2/service/datasync/types"
)

var _ bytes.Buffer
var _ awserr.Error

// CancelTaskExecutionMarshaler defines marshaler for CancelTaskExecution operation
type CancelTaskExecutionMarshaler struct {
	Input *types.CancelTaskExecutionInput
}

// CreateAgentMarshaler defines marshaler for CreateAgent operation
type CreateAgentMarshaler struct {
	Input *types.CreateAgentInput
}

// CreateLocationEfsMarshaler defines marshaler for CreateLocationEfs operation
type CreateLocationEfsMarshaler struct {
	Input *types.CreateLocationEfsInput
}

// CreateLocationNfsMarshaler defines marshaler for CreateLocationNfs operation
type CreateLocationNfsMarshaler struct {
	Input *types.CreateLocationNfsInput
}

// CreateLocationS3Marshaler defines marshaler for CreateLocationS3 operation
type CreateLocationS3Marshaler struct {
	Input *types.CreateLocationS3Input
}

// CreateLocationSmbMarshaler defines marshaler for CreateLocationSmb operation
type CreateLocationSmbMarshaler struct {
	Input *types.CreateLocationSmbInput
}

// CreateTaskMarshaler defines marshaler for CreateTask operation
type CreateTaskMarshaler struct {
	Input *types.CreateTaskInput
}

// DeleteAgentMarshaler defines marshaler for DeleteAgent operation
type DeleteAgentMarshaler struct {
	Input *types.DeleteAgentInput
}

// DeleteLocationMarshaler defines marshaler for DeleteLocation operation
type DeleteLocationMarshaler struct {
	Input *types.DeleteLocationInput
}

// DeleteTaskMarshaler defines marshaler for DeleteTask operation
type DeleteTaskMarshaler struct {
	Input *types.DeleteTaskInput
}

// DescribeAgentMarshaler defines marshaler for DescribeAgent operation
type DescribeAgentMarshaler struct {
	Input *types.DescribeAgentInput
}

// DescribeLocationEfsMarshaler defines marshaler for DescribeLocationEfs operation
type DescribeLocationEfsMarshaler struct {
	Input *types.DescribeLocationEfsInput
}

// DescribeLocationNfsMarshaler defines marshaler for DescribeLocationNfs operation
type DescribeLocationNfsMarshaler struct {
	Input *types.DescribeLocationNfsInput
}

// DescribeLocationS3Marshaler defines marshaler for DescribeLocationS3 operation
type DescribeLocationS3Marshaler struct {
	Input *types.DescribeLocationS3Input
}

// DescribeLocationSmbMarshaler defines marshaler for DescribeLocationSmb operation
type DescribeLocationSmbMarshaler struct {
	Input *types.DescribeLocationSmbInput
}

// DescribeTaskMarshaler defines marshaler for DescribeTask operation
type DescribeTaskMarshaler struct {
	Input *types.DescribeTaskInput
}

// DescribeTaskExecutionMarshaler defines marshaler for DescribeTaskExecution operation
type DescribeTaskExecutionMarshaler struct {
	Input *types.DescribeTaskExecutionInput
}

// ListAgentsMarshaler defines marshaler for ListAgents operation
type ListAgentsMarshaler struct {
	Input *types.ListAgentsInput
}

// ListLocationsMarshaler defines marshaler for ListLocations operation
type ListLocationsMarshaler struct {
	Input *types.ListLocationsInput
}

// ListTagsForResourceMarshaler defines marshaler for ListTagsForResource operation
type ListTagsForResourceMarshaler struct {
	Input *types.ListTagsForResourceInput
}

// ListTaskExecutionsMarshaler defines marshaler for ListTaskExecutions operation
type ListTaskExecutionsMarshaler struct {
	Input *types.ListTaskExecutionsInput
}

// ListTasksMarshaler defines marshaler for ListTasks operation
type ListTasksMarshaler struct {
	Input *types.ListTasksInput
}

// StartTaskExecutionMarshaler defines marshaler for StartTaskExecution operation
type StartTaskExecutionMarshaler struct {
	Input *types.StartTaskExecutionInput
}

// TagResourceMarshaler defines marshaler for TagResource operation
type TagResourceMarshaler struct {
	Input *types.TagResourceInput
}

// UntagResourceMarshaler defines marshaler for UntagResource operation
type UntagResourceMarshaler struct {
	Input *types.UntagResourceInput
}

// UpdateAgentMarshaler defines marshaler for UpdateAgent operation
type UpdateAgentMarshaler struct {
	Input *types.UpdateAgentInput
}

// UpdateTaskMarshaler defines marshaler for UpdateTask operation
type UpdateTaskMarshaler struct {
	Input *types.UpdateTaskInput
}

func MarshalCancelTaskExecutionInputShapeAWSJSON(v *types.CancelTaskExecutionInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalCreateAgentInputShapeAWSJSON(v *types.CreateAgentInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalCreateLocationEfsInputShapeAWSJSON(v *types.CreateLocationEfsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalCreateLocationNfsInputShapeAWSJSON(v *types.CreateLocationNfsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalCreateLocationS3InputShapeAWSJSON(v *types.CreateLocationS3Input, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalCreateLocationSmbInputShapeAWSJSON(v *types.CreateLocationSmbInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalCreateTaskInputShapeAWSJSON(v *types.CreateTaskInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDeleteAgentInputShapeAWSJSON(v *types.DeleteAgentInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDeleteLocationInputShapeAWSJSON(v *types.DeleteLocationInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDeleteTaskInputShapeAWSJSON(v *types.DeleteTaskInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeAgentInputShapeAWSJSON(v *types.DescribeAgentInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeLocationEfsInputShapeAWSJSON(v *types.DescribeLocationEfsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeLocationNfsInputShapeAWSJSON(v *types.DescribeLocationNfsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeLocationS3InputShapeAWSJSON(v *types.DescribeLocationS3Input, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeLocationSmbInputShapeAWSJSON(v *types.DescribeLocationSmbInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeTaskInputShapeAWSJSON(v *types.DescribeTaskInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeTaskExecutionInputShapeAWSJSON(v *types.DescribeTaskExecutionInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListAgentsInputShapeAWSJSON(v *types.ListAgentsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListLocationsInputShapeAWSJSON(v *types.ListLocationsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListTagsForResourceInputShapeAWSJSON(v *types.ListTagsForResourceInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListTaskExecutionsInputShapeAWSJSON(v *types.ListTaskExecutionsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListTasksInputShapeAWSJSON(v *types.ListTasksInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalStartTaskExecutionInputShapeAWSJSON(v *types.StartTaskExecutionInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalTagResourceInputShapeAWSJSON(v *types.TagResourceInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalUntagResourceInputShapeAWSJSON(v *types.UntagResourceInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalUpdateAgentInputShapeAWSJSON(v *types.UpdateAgentInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalUpdateTaskInputShapeAWSJSON(v *types.UpdateTaskInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}
func (m CancelTaskExecutionMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCancelTaskExecutionInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CancelTaskExecutionMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CancelTaskExecution.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateAgentMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateAgentInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateAgentMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateAgent.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateLocationEfsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateLocationEfsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateLocationEfsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateLocationEfs.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateLocationNfsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateLocationNfsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateLocationNfsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateLocationNfs.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateLocationS3Marshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateLocationS3InputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateLocationS3Marshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateLocationS3.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateLocationSmbMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateLocationSmbInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateLocationSmbMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateLocationSmb.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateTaskMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateTaskInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateTaskMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateTask.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DeleteAgentMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDeleteAgentInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DeleteAgentMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DeleteAgent.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DeleteLocationMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDeleteLocationInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DeleteLocationMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DeleteLocation.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DeleteTaskMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDeleteTaskInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DeleteTaskMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DeleteTask.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeAgentMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeAgentInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeAgentMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeAgent.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeLocationEfsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeLocationEfsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeLocationEfsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeLocationEfs.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeLocationNfsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeLocationNfsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeLocationNfsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeLocationNfs.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeLocationS3Marshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeLocationS3InputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeLocationS3Marshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeLocationS3.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeLocationSmbMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeLocationSmbInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeLocationSmbMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeLocationSmb.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeTaskMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeTaskInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeTaskMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeTask.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeTaskExecutionMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeTaskExecutionInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeTaskExecutionMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeTaskExecution.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListAgentsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListAgentsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListAgentsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListAgents.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListLocationsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListLocationsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListLocationsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListLocations.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListTagsForResourceMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListTagsForResourceInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListTagsForResourceMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListTagsForResource.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListTaskExecutionsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListTaskExecutionsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListTaskExecutionsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListTaskExecutions.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListTasksMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListTasksInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListTasksMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListTasks.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m StartTaskExecutionMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalStartTaskExecutionInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m StartTaskExecutionMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "StartTaskExecution.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m TagResourceMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalTagResourceInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m TagResourceMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "TagResource.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UntagResourceMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUntagResourceInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UntagResourceMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UntagResource.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UpdateAgentMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUpdateAgentInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UpdateAgentMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UpdateAgent.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UpdateTaskMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUpdateTaskInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UpdateTaskMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UpdateTask.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}
