// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package connect

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/connect/types"
)

const opListRoutingProfiles = "ListRoutingProfiles"

// ListRoutingProfilesRequest returns a request value for making API operation for
// Amazon Connect Service.
//
// Returns an array of RoutingProfileSummary objects that includes information
// about the routing profiles in your instance.
//
//    // Example sending a request using ListRoutingProfilesRequest.
//    req := client.ListRoutingProfilesRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/connect-2017-08-08/ListRoutingProfiles
func (c *Client) ListRoutingProfilesRequest(input *types.ListRoutingProfilesInput) ListRoutingProfilesRequest {
	op := &aws.Operation{
		Name:       opListRoutingProfiles,
		HTTPMethod: "GET",
		HTTPPath:   "/routing-profiles-summary/{InstanceId}",
	}

	if input == nil {
		input = &types.ListRoutingProfilesInput{}
	}

	req := c.newRequest(op, input, &types.ListRoutingProfilesOutput{})
	return ListRoutingProfilesRequest{Request: req, Input: input, Copy: c.ListRoutingProfilesRequest}
}

// ListRoutingProfilesRequest is the request type for the
// ListRoutingProfiles API operation.
type ListRoutingProfilesRequest struct {
	*aws.Request
	Input *types.ListRoutingProfilesInput
	Copy  func(*types.ListRoutingProfilesInput) ListRoutingProfilesRequest
}

// Send marshals and sends the ListRoutingProfiles API request.
func (r ListRoutingProfilesRequest) Send(ctx context.Context) (*ListRoutingProfilesResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &ListRoutingProfilesResponse{
		ListRoutingProfilesOutput: r.Request.Data.(*types.ListRoutingProfilesOutput),
		response:                  &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// ListRoutingProfilesResponse is the response type for the
// ListRoutingProfiles API operation.
type ListRoutingProfilesResponse struct {
	*types.ListRoutingProfilesOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// ListRoutingProfiles request.
func (r *ListRoutingProfilesResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
