// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package aws_restjson service, marshal.go contains the generated operation marshalers and methods on it.

package aws_restjson

import (
	"bytes"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/awserr"
	"github.com/aws/aws-sdk-go-v2/private/protocol/jsonrpc"
	"github.com/aws/aws-sdk-go-v2/private/protocol/rest"
	"github.com/aws/aws-sdk-go-v2/service/elasticsearchservice/types"
)

var _ bytes.Buffer
var _ awserr.Error

// AddTagsMarshaler defines marshaler for AddTags operation
type AddTagsMarshaler struct {
	Input *types.AddTagsInput
}

// CancelElasticsearchServiceSoftwareUpdateMarshaler defines marshaler for CancelElasticsearchServiceSoftwareUpdate operation
type CancelElasticsearchServiceSoftwareUpdateMarshaler struct {
	Input *types.CancelElasticsearchServiceSoftwareUpdateInput
}

// CreateElasticsearchDomainMarshaler defines marshaler for CreateElasticsearchDomain operation
type CreateElasticsearchDomainMarshaler struct {
	Input *types.CreateElasticsearchDomainInput
}

// DeleteElasticsearchDomainMarshaler defines marshaler for DeleteElasticsearchDomain operation
type DeleteElasticsearchDomainMarshaler struct {
	Input *types.DeleteElasticsearchDomainInput
}

// DeleteElasticsearchServiceRoleMarshaler defines marshaler for DeleteElasticsearchServiceRole operation
type DeleteElasticsearchServiceRoleMarshaler struct {
	Input *types.DeleteElasticsearchServiceRoleInput
}

// DescribeElasticsearchDomainMarshaler defines marshaler for DescribeElasticsearchDomain operation
type DescribeElasticsearchDomainMarshaler struct {
	Input *types.DescribeElasticsearchDomainInput
}

// DescribeElasticsearchDomainConfigMarshaler defines marshaler for DescribeElasticsearchDomainConfig operation
type DescribeElasticsearchDomainConfigMarshaler struct {
	Input *types.DescribeElasticsearchDomainConfigInput
}

// DescribeElasticsearchDomainsMarshaler defines marshaler for DescribeElasticsearchDomains operation
type DescribeElasticsearchDomainsMarshaler struct {
	Input *types.DescribeElasticsearchDomainsInput
}

// DescribeElasticsearchInstanceTypeLimitsMarshaler defines marshaler for DescribeElasticsearchInstanceTypeLimits operation
type DescribeElasticsearchInstanceTypeLimitsMarshaler struct {
	Input *types.DescribeElasticsearchInstanceTypeLimitsInput
}

// DescribeReservedElasticsearchInstanceOfferingsMarshaler defines marshaler for DescribeReservedElasticsearchInstanceOfferings operation
type DescribeReservedElasticsearchInstanceOfferingsMarshaler struct {
	Input *types.DescribeReservedElasticsearchInstanceOfferingsInput
}

// DescribeReservedElasticsearchInstancesMarshaler defines marshaler for DescribeReservedElasticsearchInstances operation
type DescribeReservedElasticsearchInstancesMarshaler struct {
	Input *types.DescribeReservedElasticsearchInstancesInput
}

// GetCompatibleElasticsearchVersionsMarshaler defines marshaler for GetCompatibleElasticsearchVersions operation
type GetCompatibleElasticsearchVersionsMarshaler struct {
	Input *types.GetCompatibleElasticsearchVersionsInput
}

// GetUpgradeHistoryMarshaler defines marshaler for GetUpgradeHistory operation
type GetUpgradeHistoryMarshaler struct {
	Input *types.GetUpgradeHistoryInput
}

// GetUpgradeStatusMarshaler defines marshaler for GetUpgradeStatus operation
type GetUpgradeStatusMarshaler struct {
	Input *types.GetUpgradeStatusInput
}

// ListDomainNamesMarshaler defines marshaler for ListDomainNames operation
type ListDomainNamesMarshaler struct {
	Input *types.ListDomainNamesInput
}

// ListElasticsearchInstanceTypesMarshaler defines marshaler for ListElasticsearchInstanceTypes operation
type ListElasticsearchInstanceTypesMarshaler struct {
	Input *types.ListElasticsearchInstanceTypesInput
}

// ListElasticsearchVersionsMarshaler defines marshaler for ListElasticsearchVersions operation
type ListElasticsearchVersionsMarshaler struct {
	Input *types.ListElasticsearchVersionsInput
}

// ListTagsMarshaler defines marshaler for ListTags operation
type ListTagsMarshaler struct {
	Input *types.ListTagsInput
}

// PurchaseReservedElasticsearchInstanceOfferingMarshaler defines marshaler for PurchaseReservedElasticsearchInstanceOffering operation
type PurchaseReservedElasticsearchInstanceOfferingMarshaler struct {
	Input *types.PurchaseReservedElasticsearchInstanceOfferingInput
}

// RemoveTagsMarshaler defines marshaler for RemoveTags operation
type RemoveTagsMarshaler struct {
	Input *types.RemoveTagsInput
}

// StartElasticsearchServiceSoftwareUpdateMarshaler defines marshaler for StartElasticsearchServiceSoftwareUpdate operation
type StartElasticsearchServiceSoftwareUpdateMarshaler struct {
	Input *types.StartElasticsearchServiceSoftwareUpdateInput
}

// UpdateElasticsearchDomainConfigMarshaler defines marshaler for UpdateElasticsearchDomainConfig operation
type UpdateElasticsearchDomainConfigMarshaler struct {
	Input *types.UpdateElasticsearchDomainConfigInput
}

// UpgradeElasticsearchDomainMarshaler defines marshaler for UpgradeElasticsearchDomain operation
type UpgradeElasticsearchDomainMarshaler struct {
	Input *types.UpgradeElasticsearchDomainInput
}

func MarshalAddTagsInputShapeAWSREST(v *types.AddTagsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalAddTagsInputShapeAWSJSON(v *types.AddTagsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalCancelElasticsearchServiceSoftwareUpdateInputShapeAWSREST(v *types.CancelElasticsearchServiceSoftwareUpdateInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalCancelElasticsearchServiceSoftwareUpdateInputShapeAWSJSON(v *types.CancelElasticsearchServiceSoftwareUpdateInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalCreateElasticsearchDomainInputShapeAWSREST(v *types.CreateElasticsearchDomainInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalCreateElasticsearchDomainInputShapeAWSJSON(v *types.CreateElasticsearchDomainInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalDeleteElasticsearchDomainInputShapeAWSREST(v *types.DeleteElasticsearchDomainInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalDeleteElasticsearchDomainInputShapeAWSJSON(v *types.DeleteElasticsearchDomainInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalDeleteElasticsearchServiceRoleInputShapeAWSREST(v *types.DeleteElasticsearchServiceRoleInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalDeleteElasticsearchServiceRoleInputShapeAWSJSON(v *types.DeleteElasticsearchServiceRoleInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalDescribeElasticsearchDomainInputShapeAWSREST(v *types.DescribeElasticsearchDomainInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalDescribeElasticsearchDomainInputShapeAWSJSON(v *types.DescribeElasticsearchDomainInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalDescribeElasticsearchDomainConfigInputShapeAWSREST(v *types.DescribeElasticsearchDomainConfigInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalDescribeElasticsearchDomainConfigInputShapeAWSJSON(v *types.DescribeElasticsearchDomainConfigInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalDescribeElasticsearchDomainsInputShapeAWSREST(v *types.DescribeElasticsearchDomainsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalDescribeElasticsearchDomainsInputShapeAWSJSON(v *types.DescribeElasticsearchDomainsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalDescribeElasticsearchInstanceTypeLimitsInputShapeAWSREST(v *types.DescribeElasticsearchInstanceTypeLimitsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalDescribeElasticsearchInstanceTypeLimitsInputShapeAWSJSON(v *types.DescribeElasticsearchInstanceTypeLimitsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalDescribeReservedElasticsearchInstanceOfferingsInputShapeAWSREST(v *types.DescribeReservedElasticsearchInstanceOfferingsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalDescribeReservedElasticsearchInstanceOfferingsInputShapeAWSJSON(v *types.DescribeReservedElasticsearchInstanceOfferingsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalDescribeReservedElasticsearchInstancesInputShapeAWSREST(v *types.DescribeReservedElasticsearchInstancesInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalDescribeReservedElasticsearchInstancesInputShapeAWSJSON(v *types.DescribeReservedElasticsearchInstancesInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalGetCompatibleElasticsearchVersionsInputShapeAWSREST(v *types.GetCompatibleElasticsearchVersionsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalGetCompatibleElasticsearchVersionsInputShapeAWSJSON(v *types.GetCompatibleElasticsearchVersionsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalGetUpgradeHistoryInputShapeAWSREST(v *types.GetUpgradeHistoryInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalGetUpgradeHistoryInputShapeAWSJSON(v *types.GetUpgradeHistoryInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalGetUpgradeStatusInputShapeAWSREST(v *types.GetUpgradeStatusInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalGetUpgradeStatusInputShapeAWSJSON(v *types.GetUpgradeStatusInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalListDomainNamesInputShapeAWSREST(v *types.ListDomainNamesInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalListDomainNamesInputShapeAWSJSON(v *types.ListDomainNamesInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalListElasticsearchInstanceTypesInputShapeAWSREST(v *types.ListElasticsearchInstanceTypesInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalListElasticsearchInstanceTypesInputShapeAWSJSON(v *types.ListElasticsearchInstanceTypesInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalListElasticsearchVersionsInputShapeAWSREST(v *types.ListElasticsearchVersionsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalListElasticsearchVersionsInputShapeAWSJSON(v *types.ListElasticsearchVersionsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalListTagsInputShapeAWSREST(v *types.ListTagsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalListTagsInputShapeAWSJSON(v *types.ListTagsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalPurchaseReservedElasticsearchInstanceOfferingInputShapeAWSREST(v *types.PurchaseReservedElasticsearchInstanceOfferingInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalPurchaseReservedElasticsearchInstanceOfferingInputShapeAWSJSON(v *types.PurchaseReservedElasticsearchInstanceOfferingInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalRemoveTagsInputShapeAWSREST(v *types.RemoveTagsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalRemoveTagsInputShapeAWSJSON(v *types.RemoveTagsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalStartElasticsearchServiceSoftwareUpdateInputShapeAWSREST(v *types.StartElasticsearchServiceSoftwareUpdateInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalStartElasticsearchServiceSoftwareUpdateInputShapeAWSJSON(v *types.StartElasticsearchServiceSoftwareUpdateInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalUpdateElasticsearchDomainConfigInputShapeAWSREST(v *types.UpdateElasticsearchDomainConfigInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalUpdateElasticsearchDomainConfigInputShapeAWSJSON(v *types.UpdateElasticsearchDomainConfigInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}

func MarshalUpgradeElasticsearchDomainInputShapeAWSREST(v *types.UpgradeElasticsearchDomainInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	rest.Build(r)
	return nil
}
func MarshalUpgradeElasticsearchDomainInputShapeAWSJSON(v *types.UpgradeElasticsearchDomainInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	if t := rest.PayloadType(r.Params); t == "structure" || t == "" {
		jsonrpc.Build(r)
	}
	return nil
}
func (m AddTagsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalAddTagsInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalAddTagsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m AddTagsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "AddTags.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CancelElasticsearchServiceSoftwareUpdateMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCancelElasticsearchServiceSoftwareUpdateInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalCancelElasticsearchServiceSoftwareUpdateInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CancelElasticsearchServiceSoftwareUpdateMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CancelElasticsearchServiceSoftwareUpdate.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateElasticsearchDomainMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateElasticsearchDomainInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalCreateElasticsearchDomainInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateElasticsearchDomainMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateElasticsearchDomain.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DeleteElasticsearchDomainMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDeleteElasticsearchDomainInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalDeleteElasticsearchDomainInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DeleteElasticsearchDomainMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DeleteElasticsearchDomain.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DeleteElasticsearchServiceRoleMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDeleteElasticsearchServiceRoleInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalDeleteElasticsearchServiceRoleInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DeleteElasticsearchServiceRoleMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DeleteElasticsearchServiceRole.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeElasticsearchDomainMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeElasticsearchDomainInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalDescribeElasticsearchDomainInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeElasticsearchDomainMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeElasticsearchDomain.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeElasticsearchDomainConfigMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeElasticsearchDomainConfigInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalDescribeElasticsearchDomainConfigInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeElasticsearchDomainConfigMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeElasticsearchDomainConfig.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeElasticsearchDomainsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeElasticsearchDomainsInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalDescribeElasticsearchDomainsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeElasticsearchDomainsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeElasticsearchDomains.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeElasticsearchInstanceTypeLimitsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeElasticsearchInstanceTypeLimitsInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalDescribeElasticsearchInstanceTypeLimitsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeElasticsearchInstanceTypeLimitsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeElasticsearchInstanceTypeLimits.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeReservedElasticsearchInstanceOfferingsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeReservedElasticsearchInstanceOfferingsInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalDescribeReservedElasticsearchInstanceOfferingsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeReservedElasticsearchInstanceOfferingsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeReservedElasticsearchInstanceOfferings.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeReservedElasticsearchInstancesMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeReservedElasticsearchInstancesInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalDescribeReservedElasticsearchInstancesInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeReservedElasticsearchInstancesMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeReservedElasticsearchInstances.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m GetCompatibleElasticsearchVersionsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalGetCompatibleElasticsearchVersionsInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalGetCompatibleElasticsearchVersionsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m GetCompatibleElasticsearchVersionsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "GetCompatibleElasticsearchVersions.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m GetUpgradeHistoryMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalGetUpgradeHistoryInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalGetUpgradeHistoryInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m GetUpgradeHistoryMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "GetUpgradeHistory.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m GetUpgradeStatusMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalGetUpgradeStatusInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalGetUpgradeStatusInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m GetUpgradeStatusMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "GetUpgradeStatus.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListDomainNamesMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListDomainNamesInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalListDomainNamesInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListDomainNamesMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListDomainNames.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListElasticsearchInstanceTypesMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListElasticsearchInstanceTypesInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalListElasticsearchInstanceTypesInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListElasticsearchInstanceTypesMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListElasticsearchInstanceTypes.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListElasticsearchVersionsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListElasticsearchVersionsInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalListElasticsearchVersionsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListElasticsearchVersionsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListElasticsearchVersions.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListTagsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListTagsInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalListTagsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListTagsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListTags.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m PurchaseReservedElasticsearchInstanceOfferingMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalPurchaseReservedElasticsearchInstanceOfferingInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalPurchaseReservedElasticsearchInstanceOfferingInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m PurchaseReservedElasticsearchInstanceOfferingMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "PurchaseReservedElasticsearchInstanceOffering.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m RemoveTagsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalRemoveTagsInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalRemoveTagsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m RemoveTagsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "RemoveTags.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m StartElasticsearchServiceSoftwareUpdateMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalStartElasticsearchServiceSoftwareUpdateInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalStartElasticsearchServiceSoftwareUpdateInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m StartElasticsearchServiceSoftwareUpdateMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "StartElasticsearchServiceSoftwareUpdate.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UpdateElasticsearchDomainConfigMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUpdateElasticsearchDomainConfigInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalUpdateElasticsearchDomainConfigInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UpdateElasticsearchDomainConfigMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UpdateElasticsearchDomainConfig.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UpgradeElasticsearchDomainMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUpgradeElasticsearchDomainInputShapeAWSREST(m.Input, r)
	if err != nil {
		r.Error = err
	}

	err = MarshalUpgradeElasticsearchDomainInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UpgradeElasticsearchDomainMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UpgradeElasticsearchDomain.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}
