// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package aws_jsonrpc service, marshal.go contains the generated operation marshalers and methods on it.

package aws_jsonrpc

import (
	"bytes"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/awserr"
	"github.com/aws/aws-sdk-go-v2/private/protocol/jsonrpc"
	"github.com/aws/aws-sdk-go-v2/service/forecastquery/types"
)

var _ bytes.Buffer
var _ awserr.Error

// QueryForecastMarshaler defines marshaler for QueryForecast operation
type QueryForecastMarshaler struct {
	Input *types.QueryForecastInput
}

func MarshalQueryForecastInputShapeAWSJSON(v *types.QueryForecastInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}
func (m QueryForecastMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalQueryForecastInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m QueryForecastMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "QueryForecast.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}
