// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package aws_jsonrpc service, marshal.go contains the generated operation marshalers and methods on it.

package aws_jsonrpc

import (
	"bytes"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/awserr"
	"github.com/aws/aws-sdk-go-v2/private/protocol/jsonrpc"
	"github.com/aws/aws-sdk-go-v2/service/cloud9/types"
)

var _ bytes.Buffer
var _ awserr.Error

// CreateEnvironmentEC2Marshaler defines marshaler for CreateEnvironmentEC2 operation
type CreateEnvironmentEC2Marshaler struct {
	Input *types.CreateEnvironmentEC2Input
}

// CreateEnvironmentMembershipMarshaler defines marshaler for CreateEnvironmentMembership operation
type CreateEnvironmentMembershipMarshaler struct {
	Input *types.CreateEnvironmentMembershipInput
}

// DeleteEnvironmentMarshaler defines marshaler for DeleteEnvironment operation
type DeleteEnvironmentMarshaler struct {
	Input *types.DeleteEnvironmentInput
}

// DeleteEnvironmentMembershipMarshaler defines marshaler for DeleteEnvironmentMembership operation
type DeleteEnvironmentMembershipMarshaler struct {
	Input *types.DeleteEnvironmentMembershipInput
}

// DescribeEnvironmentMembershipsMarshaler defines marshaler for DescribeEnvironmentMemberships operation
type DescribeEnvironmentMembershipsMarshaler struct {
	Input *types.DescribeEnvironmentMembershipsInput
}

// DescribeEnvironmentStatusMarshaler defines marshaler for DescribeEnvironmentStatus operation
type DescribeEnvironmentStatusMarshaler struct {
	Input *types.DescribeEnvironmentStatusInput
}

// DescribeEnvironmentsMarshaler defines marshaler for DescribeEnvironments operation
type DescribeEnvironmentsMarshaler struct {
	Input *types.DescribeEnvironmentsInput
}

// ListEnvironmentsMarshaler defines marshaler for ListEnvironments operation
type ListEnvironmentsMarshaler struct {
	Input *types.ListEnvironmentsInput
}

// UpdateEnvironmentMarshaler defines marshaler for UpdateEnvironment operation
type UpdateEnvironmentMarshaler struct {
	Input *types.UpdateEnvironmentInput
}

// UpdateEnvironmentMembershipMarshaler defines marshaler for UpdateEnvironmentMembership operation
type UpdateEnvironmentMembershipMarshaler struct {
	Input *types.UpdateEnvironmentMembershipInput
}

func MarshalCreateEnvironmentEC2InputShapeAWSJSON(v *types.CreateEnvironmentEC2Input, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalCreateEnvironmentMembershipInputShapeAWSJSON(v *types.CreateEnvironmentMembershipInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDeleteEnvironmentInputShapeAWSJSON(v *types.DeleteEnvironmentInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDeleteEnvironmentMembershipInputShapeAWSJSON(v *types.DeleteEnvironmentMembershipInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeEnvironmentMembershipsInputShapeAWSJSON(v *types.DescribeEnvironmentMembershipsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeEnvironmentStatusInputShapeAWSJSON(v *types.DescribeEnvironmentStatusInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDescribeEnvironmentsInputShapeAWSJSON(v *types.DescribeEnvironmentsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListEnvironmentsInputShapeAWSJSON(v *types.ListEnvironmentsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalUpdateEnvironmentInputShapeAWSJSON(v *types.UpdateEnvironmentInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalUpdateEnvironmentMembershipInputShapeAWSJSON(v *types.UpdateEnvironmentMembershipInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}
func (m CreateEnvironmentEC2Marshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateEnvironmentEC2InputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateEnvironmentEC2Marshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateEnvironmentEC2.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateEnvironmentMembershipMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateEnvironmentMembershipInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateEnvironmentMembershipMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateEnvironmentMembership.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DeleteEnvironmentMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDeleteEnvironmentInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DeleteEnvironmentMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DeleteEnvironment.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DeleteEnvironmentMembershipMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDeleteEnvironmentMembershipInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DeleteEnvironmentMembershipMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DeleteEnvironmentMembership.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeEnvironmentMembershipsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeEnvironmentMembershipsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeEnvironmentMembershipsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeEnvironmentMemberships.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeEnvironmentStatusMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeEnvironmentStatusInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeEnvironmentStatusMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeEnvironmentStatus.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DescribeEnvironmentsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDescribeEnvironmentsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DescribeEnvironmentsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DescribeEnvironments.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListEnvironmentsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListEnvironmentsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListEnvironmentsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListEnvironments.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UpdateEnvironmentMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUpdateEnvironmentInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UpdateEnvironmentMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UpdateEnvironment.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UpdateEnvironmentMembershipMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUpdateEnvironmentMembershipInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UpdateEnvironmentMembershipMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UpdateEnvironmentMembership.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}
