// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package aws_jsonrpc service, marshal.go contains the generated operation marshalers and methods on it.

package aws_jsonrpc

import (
	"bytes"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/awserr"
	"github.com/aws/aws-sdk-go-v2/private/protocol/jsonrpc"
	"github.com/aws/aws-sdk-go-v2/service/route53resolver/types"
)

var _ bytes.Buffer
var _ awserr.Error

// AssociateResolverEndpointIpAddressMarshaler defines marshaler for AssociateResolverEndpointIpAddress operation
type AssociateResolverEndpointIpAddressMarshaler struct {
	Input *types.AssociateResolverEndpointIpAddressInput
}

// AssociateResolverRuleMarshaler defines marshaler for AssociateResolverRule operation
type AssociateResolverRuleMarshaler struct {
	Input *types.AssociateResolverRuleInput
}

// CreateResolverEndpointMarshaler defines marshaler for CreateResolverEndpoint operation
type CreateResolverEndpointMarshaler struct {
	Input *types.CreateResolverEndpointInput
}

// CreateResolverRuleMarshaler defines marshaler for CreateResolverRule operation
type CreateResolverRuleMarshaler struct {
	Input *types.CreateResolverRuleInput
}

// DeleteResolverEndpointMarshaler defines marshaler for DeleteResolverEndpoint operation
type DeleteResolverEndpointMarshaler struct {
	Input *types.DeleteResolverEndpointInput
}

// DeleteResolverRuleMarshaler defines marshaler for DeleteResolverRule operation
type DeleteResolverRuleMarshaler struct {
	Input *types.DeleteResolverRuleInput
}

// DisassociateResolverEndpointIpAddressMarshaler defines marshaler for DisassociateResolverEndpointIpAddress operation
type DisassociateResolverEndpointIpAddressMarshaler struct {
	Input *types.DisassociateResolverEndpointIpAddressInput
}

// DisassociateResolverRuleMarshaler defines marshaler for DisassociateResolverRule operation
type DisassociateResolverRuleMarshaler struct {
	Input *types.DisassociateResolverRuleInput
}

// GetResolverEndpointMarshaler defines marshaler for GetResolverEndpoint operation
type GetResolverEndpointMarshaler struct {
	Input *types.GetResolverEndpointInput
}

// GetResolverRuleMarshaler defines marshaler for GetResolverRule operation
type GetResolverRuleMarshaler struct {
	Input *types.GetResolverRuleInput
}

// GetResolverRuleAssociationMarshaler defines marshaler for GetResolverRuleAssociation operation
type GetResolverRuleAssociationMarshaler struct {
	Input *types.GetResolverRuleAssociationInput
}

// GetResolverRulePolicyMarshaler defines marshaler for GetResolverRulePolicy operation
type GetResolverRulePolicyMarshaler struct {
	Input *types.GetResolverRulePolicyInput
}

// ListResolverEndpointIpAddressesMarshaler defines marshaler for ListResolverEndpointIpAddresses operation
type ListResolverEndpointIpAddressesMarshaler struct {
	Input *types.ListResolverEndpointIpAddressesInput
}

// ListResolverEndpointsMarshaler defines marshaler for ListResolverEndpoints operation
type ListResolverEndpointsMarshaler struct {
	Input *types.ListResolverEndpointsInput
}

// ListResolverRuleAssociationsMarshaler defines marshaler for ListResolverRuleAssociations operation
type ListResolverRuleAssociationsMarshaler struct {
	Input *types.ListResolverRuleAssociationsInput
}

// ListResolverRulesMarshaler defines marshaler for ListResolverRules operation
type ListResolverRulesMarshaler struct {
	Input *types.ListResolverRulesInput
}

// ListTagsForResourceMarshaler defines marshaler for ListTagsForResource operation
type ListTagsForResourceMarshaler struct {
	Input *types.ListTagsForResourceInput
}

// PutResolverRulePolicyMarshaler defines marshaler for PutResolverRulePolicy operation
type PutResolverRulePolicyMarshaler struct {
	Input *types.PutResolverRulePolicyInput
}

// TagResourceMarshaler defines marshaler for TagResource operation
type TagResourceMarshaler struct {
	Input *types.TagResourceInput
}

// UntagResourceMarshaler defines marshaler for UntagResource operation
type UntagResourceMarshaler struct {
	Input *types.UntagResourceInput
}

// UpdateResolverEndpointMarshaler defines marshaler for UpdateResolverEndpoint operation
type UpdateResolverEndpointMarshaler struct {
	Input *types.UpdateResolverEndpointInput
}

// UpdateResolverRuleMarshaler defines marshaler for UpdateResolverRule operation
type UpdateResolverRuleMarshaler struct {
	Input *types.UpdateResolverRuleInput
}

func MarshalAssociateResolverEndpointIpAddressInputShapeAWSJSON(v *types.AssociateResolverEndpointIpAddressInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalAssociateResolverRuleInputShapeAWSJSON(v *types.AssociateResolverRuleInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalCreateResolverEndpointInputShapeAWSJSON(v *types.CreateResolverEndpointInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalCreateResolverRuleInputShapeAWSJSON(v *types.CreateResolverRuleInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDeleteResolverEndpointInputShapeAWSJSON(v *types.DeleteResolverEndpointInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDeleteResolverRuleInputShapeAWSJSON(v *types.DeleteResolverRuleInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDisassociateResolverEndpointIpAddressInputShapeAWSJSON(v *types.DisassociateResolverEndpointIpAddressInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalDisassociateResolverRuleInputShapeAWSJSON(v *types.DisassociateResolverRuleInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalGetResolverEndpointInputShapeAWSJSON(v *types.GetResolverEndpointInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalGetResolverRuleInputShapeAWSJSON(v *types.GetResolverRuleInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalGetResolverRuleAssociationInputShapeAWSJSON(v *types.GetResolverRuleAssociationInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalGetResolverRulePolicyInputShapeAWSJSON(v *types.GetResolverRulePolicyInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListResolverEndpointIpAddressesInputShapeAWSJSON(v *types.ListResolverEndpointIpAddressesInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListResolverEndpointsInputShapeAWSJSON(v *types.ListResolverEndpointsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListResolverRuleAssociationsInputShapeAWSJSON(v *types.ListResolverRuleAssociationsInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListResolverRulesInputShapeAWSJSON(v *types.ListResolverRulesInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalListTagsForResourceInputShapeAWSJSON(v *types.ListTagsForResourceInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalPutResolverRulePolicyInputShapeAWSJSON(v *types.PutResolverRulePolicyInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalTagResourceInputShapeAWSJSON(v *types.TagResourceInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalUntagResourceInputShapeAWSJSON(v *types.UntagResourceInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalUpdateResolverEndpointInputShapeAWSJSON(v *types.UpdateResolverEndpointInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}

func MarshalUpdateResolverRuleInputShapeAWSJSON(v *types.UpdateResolverRuleInput, r *aws.Request) error {
	// delegate to reflection based marshaling
	jsonrpc.Build(r)
	return nil
}
func (m AssociateResolverEndpointIpAddressMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalAssociateResolverEndpointIpAddressInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m AssociateResolverEndpointIpAddressMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "AssociateResolverEndpointIpAddress.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m AssociateResolverRuleMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalAssociateResolverRuleInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m AssociateResolverRuleMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "AssociateResolverRule.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateResolverEndpointMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateResolverEndpointInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateResolverEndpointMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateResolverEndpoint.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m CreateResolverRuleMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalCreateResolverRuleInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m CreateResolverRuleMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "CreateResolverRule.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DeleteResolverEndpointMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDeleteResolverEndpointInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DeleteResolverEndpointMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DeleteResolverEndpoint.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DeleteResolverRuleMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDeleteResolverRuleInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DeleteResolverRuleMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DeleteResolverRule.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DisassociateResolverEndpointIpAddressMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDisassociateResolverEndpointIpAddressInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DisassociateResolverEndpointIpAddressMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DisassociateResolverEndpointIpAddress.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m DisassociateResolverRuleMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalDisassociateResolverRuleInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m DisassociateResolverRuleMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "DisassociateResolverRule.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m GetResolverEndpointMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalGetResolverEndpointInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m GetResolverEndpointMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "GetResolverEndpoint.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m GetResolverRuleMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalGetResolverRuleInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m GetResolverRuleMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "GetResolverRule.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m GetResolverRuleAssociationMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalGetResolverRuleAssociationInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m GetResolverRuleAssociationMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "GetResolverRuleAssociation.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m GetResolverRulePolicyMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalGetResolverRulePolicyInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m GetResolverRulePolicyMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "GetResolverRulePolicy.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListResolverEndpointIpAddressesMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListResolverEndpointIpAddressesInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListResolverEndpointIpAddressesMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListResolverEndpointIpAddresses.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListResolverEndpointsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListResolverEndpointsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListResolverEndpointsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListResolverEndpoints.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListResolverRuleAssociationsMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListResolverRuleAssociationsInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListResolverRuleAssociationsMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListResolverRuleAssociations.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListResolverRulesMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListResolverRulesInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListResolverRulesMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListResolverRules.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m ListTagsForResourceMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalListTagsForResourceInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m ListTagsForResourceMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "ListTagsForResource.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m PutResolverRulePolicyMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalPutResolverRulePolicyInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m PutResolverRulePolicyMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "PutResolverRulePolicy.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m TagResourceMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalTagResourceInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m TagResourceMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "TagResource.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UntagResourceMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUntagResourceInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UntagResourceMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UntagResource.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UpdateResolverEndpointMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUpdateResolverEndpointInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UpdateResolverEndpointMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UpdateResolverEndpoint.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}

func (m UpdateResolverRuleMarshaler) MarshalOperation(r *aws.Request) {
	var err error

	err = MarshalUpdateResolverRuleInputShapeAWSJSON(m.Input, r)
	if err != nil {
		r.Error = err
	}

}

// GetNamedBuildHandler returns a Named Build Handler for an operation marshal function
func (m UpdateResolverRuleMarshaler) GetNamedBuildHandler() aws.NamedHandler {
	const BuildHandler = "UpdateResolverRule.BuildHandler"
	return aws.NamedHandler{
		Name: BuildHandler,
		Fn:   m.MarshalOperation,
	}
}
